/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_andresmoncada;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Dell
 */
public class Universo extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Universo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpm_mundos = new javax.swing.JPopupMenu();
        jmi_madd = new javax.swing.JMenuItem();
        jmi_mmod = new javax.swing.JMenuItem();
        jmi_mdel = new javax.swing.JMenuItem();
        jpm_criaturas = new javax.swing.JPopupMenu();
        jmi_cadd = new javax.swing.JMenuItem();
        jmi_cmod = new javax.swing.JMenuItem();
        jmi_cdel = new javax.swing.JMenuItem();
        jd_madd = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        agregarmundo = new javax.swing.JButton();
        tf_mnom = new javax.swing.JTextField();
        tf_mpeso = new javax.swing.JTextField();
        jd_cadd = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_cnom = new javax.swing.JTextField();
        tf_cene = new javax.swing.JTextField();
        tf_cedad = new javax.swing.JTextField();
        tf_creg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_cpob = new javax.swing.JTextField();
        tf_cpeso = new javax.swing.JTextField();
        agregarcriatura = new javax.swing.JButton();
        jd_cmod = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tf_modnom = new javax.swing.JTextField();
        tf_modene = new javax.swing.JTextField();
        tf_modedad = new javax.swing.JTextField();
        tf_modpob = new javax.swing.JTextField();
        tf_modreg = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jpm_uni = new javax.swing.JPopupMenu();
        jmi_udel = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_mundos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_uni = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_criaturas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        agregarbol = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        label_peso = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jmi_madd.setText("Agregar mundo");
        jmi_madd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_maddActionPerformed(evt);
            }
        });
        jpm_mundos.add(jmi_madd);

        jmi_mmod.setText("Modificar mundo");
        jmi_mmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mmodActionPerformed(evt);
            }
        });
        jpm_mundos.add(jmi_mmod);

        jmi_mdel.setText("Eliminar mundo");
        jmi_mdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mdelActionPerformed(evt);
            }
        });
        jpm_mundos.add(jmi_mdel);

        jmi_cadd.setText("Agregar criatura");
        jmi_cadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_caddActionPerformed(evt);
            }
        });
        jpm_criaturas.add(jmi_cadd);

        jmi_cmod.setText("Modificar criatura");
        jmi_cmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cmodActionPerformed(evt);
            }
        });
        jpm_criaturas.add(jmi_cmod);

        jmi_cdel.setText("Eliminar criatura");
        jmi_cdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cdelActionPerformed(evt);
            }
        });
        jpm_criaturas.add(jmi_cdel);

        jLabel4.setText("Nombre de la tortuga");

        jLabel5.setText("Peso");

        agregarmundo.setText("Agregar");
        agregarmundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarmundoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_maddLayout = new javax.swing.GroupLayout(jd_madd.getContentPane());
        jd_madd.getContentPane().setLayout(jd_maddLayout);
        jd_maddLayout.setHorizontalGroup(
            jd_maddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_maddLayout.createSequentialGroup()
                .addGroup(jd_maddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_maddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_maddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_maddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_mpeso, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(tf_mnom)))
                    .addGroup(jd_maddLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(agregarmundo)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jd_maddLayout.setVerticalGroup(
            jd_maddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_maddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_maddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_mnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_maddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_mpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(agregarmundo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Nombre de la raza");

        jLabel7.setText("Numero de energía");

        jLabel8.setText("Edad máxima");

        jLabel9.setText("Nombre de la región");

        jLabel10.setText("Población");

        jLabel11.setText("Peso");

        agregarcriatura.setText("Agregar");
        agregarcriatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarcriaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_caddLayout = new javax.swing.GroupLayout(jd_cadd.getContentPane());
        jd_cadd.getContentPane().setLayout(jd_caddLayout);
        jd_caddLayout.setHorizontalGroup(
            jd_caddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_caddLayout.createSequentialGroup()
                .addGroup(jd_caddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_caddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_caddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jd_caddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_cnom)
                            .addComponent(tf_cene)
                            .addComponent(tf_cedad)
                            .addComponent(tf_creg)
                            .addComponent(tf_cpob)
                            .addComponent(tf_cpeso, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                    .addGroup(jd_caddLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(agregarcriatura)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jd_caddLayout.setVerticalGroup(
            jd_caddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_caddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_caddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_cnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_caddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_cene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_caddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_cedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_caddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_creg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_caddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_cpob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_caddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_cpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(agregarcriatura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setText("Raza");

        jLabel19.setText("Energía");

        jLabel20.setText("Edad máxima");

        jLabel21.setText("Población");

        jLabel22.setText("Región");

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_cmodLayout = new javax.swing.GroupLayout(jd_cmod.getContentPane());
        jd_cmod.getContentPane().setLayout(jd_cmodLayout);
        jd_cmodLayout.setHorizontalGroup(
            jd_cmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_cmodLayout.createSequentialGroup()
                .addGroup(jd_cmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_cmodLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_cmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addGroup(jd_cmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(jd_cmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_modnom)
                            .addComponent(tf_modene)
                            .addComponent(tf_modedad)
                            .addComponent(tf_modpob)
                            .addComponent(tf_modreg, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                    .addGroup(jd_cmodLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton2)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jd_cmodLayout.setVerticalGroup(
            jd_cmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_cmodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_cmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_modnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_cmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_modene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_cmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_modedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_cmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_modpob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_cmodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_modreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jmi_udel.setText("Eliminar");
        jmi_udel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_udelActionPerformed(evt);
            }
        });
        jpm_uni.add(jmi_udel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_mundos.setModel(new DefaultListModel());
        jl_mundos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_mundosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_mundos);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Universo");
        jt_uni.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_uni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_uniMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_uni);

        jl_criaturas.setModel(new DefaultListModel());
        jl_criaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_criaturasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl_criaturas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mundos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Criaturas");

        jLabel3.setText("Presione clic derecho en una lista para ver sus opciones");

        jLabel12.setText("Al escoger un mundo se mostrarán sus criaturas en la lista");

        agregarbol.setText("Agregar mundo al árbol");
        agregarbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarbolActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Peso:");

        label_peso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_peso.setText("0");

        jLabel15.setText("Agregara el mundo seleccionado");

        jLabel16.setText("y todas sus criaturas");

        jButton1.setText("Agregar criatura al árbol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Modificar se hace en las listas");

        jLabel18.setText("universo12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(agregarbol)
                                            .addComponent(jLabel15)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel16))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(agregarbol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addGap(54, 54, 54)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13)
                            .addComponent(label_peso))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jl_mundosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_mundosMouseClicked
        if (evt.isMetaDown()){
            jpm_mundos.show(jl_mundos, evt.getX(), evt.getY());
        }else if(jl_mundos.getSelectedIndex()>=0){
            DefaultListModel modelom = (DefaultListModel)jl_mundos.getModel();
            DefaultListModel modeloc = new DefaultListModel();
            for (int i = 0; i < ((Mundo)modelom.getElementAt(jl_mundos.getSelectedIndex())).getCriaturas().size(); i++) {
                modeloc.addElement(((Mundo)modelom.getElementAt(jl_mundos.getSelectedIndex())).getCriaturas().get(i));
            }
            jl_criaturas.setModel(modeloc);
        }
    }//GEN-LAST:event_jl_mundosMouseClicked

    private void jl_criaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_criaturasMouseClicked
        if (evt.isMetaDown()){
            jpm_criaturas.show(jl_criaturas, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jl_criaturasMouseClicked

    private void jmi_maddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_maddActionPerformed
        jd_madd.setModal(true);
        jd_madd.pack();
        jd_madd.setLocationRelativeTo(this);
        jd_madd.setVisible(true);
    }//GEN-LAST:event_jmi_maddActionPerformed

    private void jmi_caddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_caddActionPerformed
        jd_cadd.setModal(true);
        jd_cadd.pack();
        jd_cadd.setLocationRelativeTo(this);
        jd_cadd.setVisible(true);
    }//GEN-LAST:event_jmi_caddActionPerformed

    private void jmi_mmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mmodActionPerformed
        if(jl_mundos.getSelectedIndex() >= 0){
            String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre nuevo");
            DefaultListModel modelo = (DefaultListModel) jl_mundos.getModel();
            ((Mundo)modelo.getElementAt(jl_mundos.getSelectedIndex())).setNombre(nombre);
            jl_mundos.setModel(modelo);
        }else
            JOptionPane.showMessageDialog(this, "No hay un mundo seleccionado");
    }//GEN-LAST:event_jmi_mmodActionPerformed

    private void jmi_cmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cmodActionPerformed
        if(jl_criaturas.getSelectedIndex() >= 0){
            jd_cmod.setModal(true);
            jd_cmod.pack();
            jd_cmod.setLocationRelativeTo(this);
            DefaultListModel modelo = (DefaultListModel)jl_criaturas.getModel();
            tf_modnom.setText(((Criatura)modelo.getElementAt(jl_criaturas.getSelectedIndex())).getRaza());
            tf_modene.setText(String.valueOf(((Criatura)modelo.getElementAt(jl_criaturas.getSelectedIndex())).getEnergia()));
            tf_modedad.setText(String.valueOf(((Criatura)modelo.getElementAt(jl_criaturas.getSelectedIndex())).getEdadmax()));
            tf_modpob.setText(String.valueOf(((Criatura)modelo.getElementAt(jl_criaturas.getSelectedIndex())).getPoblacion()));
            tf_modreg.setText(((Criatura)modelo.getElementAt(jl_criaturas.getSelectedIndex())).getRegion());
            jd_cmod.setVisible(true);
        }else
            JOptionPane.showMessageDialog(this, "No hay una criatura seleccionada");
    }//GEN-LAST:event_jmi_cmodActionPerformed

    private void jmi_mdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mdelActionPerformed
        if(jl_mundos.getSelectedIndex() >= 0){
            DefaultListModel modelo = (DefaultListModel)jl_mundos.getModel();
            int resp = JOptionPane.showConfirmDialog(this, "Esta seguro que desea eliminar " + modelo.getElementAt(jl_mundos.getSelectedIndex()).toString()+"?","Confirm",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(resp == JOptionPane.OK_OPTION){
            
            modelo.remove(jl_mundos.getSelectedIndex());
        }
        }else
            JOptionPane.showMessageDialog(this, "No hay un mundo seleccionado");
    }//GEN-LAST:event_jmi_mdelActionPerformed

    private void agregarmundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarmundoActionPerformed
        String nombre = tf_mnom.getText();
        boolean v = true;
        DefaultListModel modelo = (DefaultListModel) jl_mundos.getModel();
        for (int i = 0; i < modelo.getSize(); i++) {
            if(((Mundo)modelo.getElementAt(i)).getNombre().equals(nombre)){
                v = false;
                break;
            }
        }
        if(v){
            try {
                long peso = Long.parseLong(tf_mpeso.getText());
                modelo.addElement(new Mundo(nombre,peso));
                jl_mundos.setModel(modelo);
                tf_mnom.setText("");
                tf_mpeso.setText("");
                jd_madd.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Se produjo un error agregando a la lista");
            }
        }else
            JOptionPane.showMessageDialog(this, "Ya existe un mundo con este nombre");
    }//GEN-LAST:event_agregarmundoActionPerformed

    private void agregarcriaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarcriaturaActionPerformed
        if(jl_mundos.getSelectedIndex()>= 0){
            try {
                String raza = tf_cnom.getText();
                int energia = Integer.parseInt(tf_cene.getText());
                int edad = Integer.parseInt(tf_cedad.getText());
                String region = tf_creg.getText();
                long poblacion = Long.parseLong(tf_cpob.getText());
                int peso = Integer.parseInt(tf_cpeso.getText());
                DefaultListModel modelom = (DefaultListModel) jl_mundos.getModel();
                DefaultListModel modeloc = (DefaultListModel) jl_criaturas.getModel();
                ((Mundo)modelom.getElementAt(jl_mundos.getSelectedIndex())).getCriaturas().add(new Criatura(raza, energia, edad, region, poblacion, peso));
                modeloc.addElement(((Mundo)modelom.getElementAt(jl_mundos.getSelectedIndex())).getCriaturas().get(((Mundo)modelom.getElementAt(jl_mundos.getSelectedIndex())).getCriaturas().size()-1));
                jl_criaturas.setModel(modeloc);
                tf_cnom.setText("");
                tf_cedad.setText("");
                tf_cene.setText("");
                tf_cpeso.setText("");
                tf_cpob.setText("");
                tf_creg.setText("");
                jd_cadd.setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Se produjo un error agregando a la lista");
            }
        }else
            JOptionPane.showMessageDialog(this, "Seleccione un mundo primero");
    }//GEN-LAST:event_agregarcriaturaActionPerformed

    private void jmi_cdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cdelActionPerformed
        if(jl_criaturas.getSelectedIndex() >= 0){
            DefaultListModel modelo = (DefaultListModel)jl_criaturas.getModel();
            int resp = JOptionPane.showConfirmDialog(this, "Esta seguro que desea eliminar " + modelo.getElementAt(jl_criaturas.getSelectedIndex()).toString()+"?","Confirm",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(resp == JOptionPane.OK_OPTION){
            
            modelo.remove(jl_criaturas.getSelectedIndex());
        }
        }else
            JOptionPane.showMessageDialog(this, "No hay una criatura seleccionada");
    }//GEN-LAST:event_jmi_cdelActionPerformed

    private void agregarbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarbolActionPerformed
        if(jl_mundos.getSelectedIndex() >= 0){
            DefaultTreeModel modArbol = (DefaultTreeModel)jt_uni.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)modArbol.getRoot();
            DefaultListModel modm = (DefaultListModel)jl_mundos.getModel();
            DefaultListModel modc = (DefaultListModel)jl_criaturas.getModel();
            String tortuga;
            tortuga = "Mundo Disco - " + ((Mundo)modm.get(jl_mundos.getSelectedIndex())).getNombre();
            boolean v = true;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if(raiz.getChildAt(i).toString().equals(tortuga)){
                        JOptionPane.showMessageDialog(this, "Ya se agrego este mundo");
                        v = false;
                        break;
                }
            }
            if(v){
                DefaultMutableTreeNode m = new DefaultMutableTreeNode(tortuga);
                for (int i = 0; i < modc.size(); i++) {
                    DefaultMutableTreeNode c = new DefaultMutableTreeNode((Criatura)modc.getElementAt(i));
                    m.add(c);
                }
                raiz.add(m);
            }
            modArbol.reload();
        }else
            JOptionPane.showMessageDialog(this, "No hay mundo seleccionado");
        revisarPeso();
    }//GEN-LAST:event_agregarbolActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jl_criaturas.getSelectedIndex() >= 0){
            DefaultTreeModel modArbol = (DefaultTreeModel)jt_uni.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)modArbol.getRoot();
            DefaultListModel modm = (DefaultListModel)jl_mundos.getModel();
            DefaultListModel modc = (DefaultListModel)jl_criaturas.getModel();
            String raza, tortuga;
            tortuga = "Mundo Disco - " + ((Mundo)modm.get(jl_mundos.getSelectedIndex())).getNombre();
            raza = ((Criatura)((Mundo)modm.get(jl_mundos.getSelectedIndex())).getCriaturas().get(jl_criaturas.getSelectedIndex())).getRaza();
            int v = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if(raiz.getChildAt(i).toString().equals(tortuga)){
                    for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                        if(raiz.getChildAt(i).getChildAt(j).toString().equals(raza)){
                            v = 2;
                        }
                    }
                    if(v == 2){
                        JOptionPane.showMessageDialog(this, "Ya se agrego esta criatura");
                        break;
                    }
                    v = 1;
                    DefaultMutableTreeNode c = new DefaultMutableTreeNode((Criatura)modc.getElementAt(jl_criaturas.getSelectedIndex()));
                    ((DefaultMutableTreeNode)raiz.getChildAt(i)).add(c);
                    break;
                }
            }
            if(v == -1){
                DefaultMutableTreeNode m = new DefaultMutableTreeNode(tortuga);
                DefaultMutableTreeNode c = new DefaultMutableTreeNode((Criatura)modc.getElementAt(jl_criaturas.getSelectedIndex()));
                m.add(c);
                raiz.add(m);
            }
            modArbol.reload();
        }else
            JOptionPane.showMessageDialog(this, "No hay persona seleccionada");
        revisarPeso();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jt_uniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_uniMouseClicked
        if(evt.isMetaDown()){
            int row = jt_uni.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_uni.setSelectionRow(row);
            Object v1 = jt_uni.getSelectionPath().getLastPathComponent();
            nodo = (DefaultMutableTreeNode) v1;
            jpm_uni.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jt_uniMouseClicked

    private void jmi_udelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_udelActionPerformed
        DefaultTreeModel m = (DefaultTreeModel)jt_uni.getModel();
        if(nodo.getUserObject() instanceof Criatura){
            m.removeNodeFromParent(nodo);
            m.reload();
        }else if(nodo.getUserObject() instanceof String && !nodo.getUserObject().equals("Universo")){
            m.removeNodeFromParent(nodo);
            m.reload();
        }else
            JOptionPane.showMessageDialog(this, "No");
        revisarPeso();
    }//GEN-LAST:event_jmi_udelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultListModel modelo = (DefaultListModel)jl_criaturas.getModel();
        ((Criatura)modelo.getElementAt(jl_criaturas.getSelectedIndex())).setRaza(tf_modnom.getText());
        ((Criatura)modelo.getElementAt(jl_criaturas.getSelectedIndex())).setRegion(tf_modreg.getText());
        ((Criatura)modelo.getElementAt(jl_criaturas.getSelectedIndex())).setEnergia(Integer.parseInt(tf_modene.getText()));
        ((Criatura)modelo.getElementAt(jl_criaturas.getSelectedIndex())).setEdadmax(Integer.parseInt(tf_modedad.getText()));
        ((Criatura)modelo.getElementAt(jl_criaturas.getSelectedIndex())).setPoblacion(Long.parseLong(tf_modpob.getText()));
        jl_criaturas.setModel(modelo);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void revisarPeso(){
        peso = 0;
        DefaultTreeModel modArbol = (DefaultTreeModel)jt_uni.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode)modArbol.getRoot();
        DefaultListModel modm = (DefaultListModel)jl_mundos.getModel();
        for (int i = 0; i < raiz.getChildCount(); i++) {
            for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                peso += ((Criatura)raiz.getChildAt(i).getChildAt(j)).getPoblacion()*((Criatura)raiz.getChildAt(i).getChildAt(j)).getPeso();
            }
            for (int j = 0; j < modm.size(); j++) {
                if(raiz.getChildAt(i).equals("Mundo Disco - " + ((Mundo)modm.getElementAt(j)).getNombre())){
                    peso += ((Mundo)modm.getElementAt(j)).getPeso();
                    break;
                }
            }
        }
        label_peso.setText(String.valueOf(peso));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Universo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Universo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Universo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Universo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Universo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarbol;
    private javax.swing.JButton agregarcriatura;
    private javax.swing.JButton agregarmundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_cadd;
    private javax.swing.JDialog jd_cmod;
    private javax.swing.JDialog jd_madd;
    private javax.swing.JList<String> jl_criaturas;
    private javax.swing.JList<String> jl_mundos;
    private javax.swing.JMenuItem jmi_cadd;
    private javax.swing.JMenuItem jmi_cdel;
    private javax.swing.JMenuItem jmi_cmod;
    private javax.swing.JMenuItem jmi_madd;
    private javax.swing.JMenuItem jmi_mdel;
    private javax.swing.JMenuItem jmi_mmod;
    private javax.swing.JMenuItem jmi_udel;
    private javax.swing.JPopupMenu jpm_criaturas;
    private javax.swing.JPopupMenu jpm_mundos;
    private javax.swing.JPopupMenu jpm_uni;
    private javax.swing.JTree jt_uni;
    private javax.swing.JLabel label_peso;
    private javax.swing.JTextField tf_cedad;
    private javax.swing.JTextField tf_cene;
    private javax.swing.JTextField tf_cnom;
    private javax.swing.JTextField tf_cpeso;
    private javax.swing.JTextField tf_cpob;
    private javax.swing.JTextField tf_creg;
    private javax.swing.JTextField tf_mnom;
    private javax.swing.JTextField tf_modedad;
    private javax.swing.JTextField tf_modene;
    private javax.swing.JTextField tf_modnom;
    private javax.swing.JTextField tf_modpob;
    private javax.swing.JTextField tf_modreg;
    private javax.swing.JTextField tf_mpeso;
    // End of variables declaration//GEN-END:variables
    private String codigo = "universo12";
    private long edad = 14000000;
    private long peso = 0;
    private DefaultMutableTreeNode nodo;
    private Criatura criatura;
}
